
# Cache terraform in between stages
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - infra/platform/k8s-eks/.terraform

before_script:
  - cd infra/platform/k8s-eks/
  - rm -rf .terraform
  - terraform --version
# used for ggoogle cloud
#  - mkdir -p ./creds
#  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  - terraform init

stages:
  - validate
  - plan
  - apply
  - audit
  - destroy

validate:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - terraform validate

plan:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: apply
  script:
#    - terraform apply -input=false "planfile"
    - terraform apply -input=false -auto-approve 
  dependencies:
    - plan
# when: manual

destroy:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: destroy
  script:
#    - terraform apply -input=false "planfile"
    - terraform destroy -input=false -auto-approve 
  dependencies:
    - apply

prowler:cis:1:
  image:
    name: aethereal/prowler:latest
  stage: audit
  script:
    - prowler -r ${AWS_DEFAULT_REGION} -f ${AWS_DEFAULT_REGION} -c check1
  dependencies:
   - apply

prowler:cis:2:
  image:
    name: aethereal/prowler:latest
  stage: audit
  script:
    - prowler -r ${AWS_DEFAULT_REGION} -f ${AWS_DEFAULT_REGION} -c check2
  dependencies:
   - apply

prowler:cis:3:
  image:
    name: aethereal/prowler:latest
  stage: audit
  script:
    - prowler -r ${AWS_DEFAULT_REGION} -f ${AWS_DEFAULT_REGION} -c check3
  dependencies:
   - apply

prowler:cis:4:
  image:
    name: aethereal/prowler:latest
  stage: audit
  script:
    - prowler -r ${AWS_DEFAULT_REGION} -f ${AWS_DEFAULT_REGION} -c check4
  dependencies:
    - apply