---
# KITCHEN_YAML="alternative_kitchen.yml" kitchen test
driver:
  name: vagrant

# provisioner:
#   name: chef_zero
provisioner:
  name: shell
  script:    'space-setup-win10.bat'

verifier:
  name: inspec

platforms:
  # - name: ubuntu-18.04
  # - name: centos-7
  - name: windows-10
    transport:
      name: winrm
    driver:
      guest: :windows
      box: StefanScherer/windows_10
  - name: windows-11
    transport:
      name: winrm
    driver:
      guest: :windows
      box: StefanScherer/windows_11
  - name: macos
    driver:
      box: GAEV/MacOS_Catalina
  # adapify/mactesting
  # start work on aws test
  # -name: windows-2012r2
  # driver:
  #   image_id: ami-xxxxxxxx
  # transport:
  #   username: ec2-user
  #   ssh_key: ../ec2_keys/US-East1.pem

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
  