apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImplbmtpbnMiDQogIG1ldHJpY3NfcGF0aDogL3Byb21ldGhldXMNCiAgc2NyYXBlX2ludGVydmFsOiAxMjBzDQogIHN0YXRpY19jb25maWdzOg0KICAgIC0gdGFyZ2V0czogWyJqZW5raW5zLnBpcGVsaW5lLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAiXQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: pipeline
