apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab-scm-collector
  name: gitlab-scm-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gitlab-scm-collector
    spec:
      containers:
      - image: hygieia-gitlab-scm-collector
        name: gitlab-scm-collector
        resources: {}
      restartPolicy: Always
status: {}
