apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sonar-codequality-collector
  name: sonar-codequality-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar-codequality-collector
    spec:
      containers:
      - env:
        - name: PROP_FILE
          value: application.properties
        - name: SONAR_CRON
          value: 0 0/5 * * * *
        - name: SONAR_URL
          value: http://a116e8fb55d3811e985de0ebf3e1312a-120804566.us-east-1.elb.amazonaws.com:9000
        - name: SONAR_USERNAME
          value: admin
        - name: SONAR_PASSWORD
          value: admin
        - name: SONAR_VERSION
          value: "7.6" 
        image: mssheldon/hygieia-sonar-codequality-collector
        name: sonar-codequality-collector
        resources: {}
      restartPolicy: Always
status: {}
